server {
    listen 80;

    location / {
        proxy_pass http://python:8000;
        client_max_body_size 10G;   
        proxy_set_header Host $host; # preserves info about original connection
        proxy_set_header X-Real-IP $remote_addr; # preserves info about original connection
    }
}
